# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4048m -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1g
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# AndroidX package structure
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Enable non-transitive R classes
android.nonTransitiveRClass=true

# Hilt
kapt.use.k2=true

# Fix for java.io.StreamCorruptedException: unexpected EOF in middle of data block
ksp.incremental=false
kapt.incremental.apt=false

# Compose
org.gradle.unsafe.configuration-cache=true
